version: '3.8'

services:
  db:
      container_name: zoss_mysql
      image: mysql:8.0
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: zoss_test
        MYSQL_ROOT_HOST: '%'
      ports:
        - "3307:3306"
      volumes:
        - db_data:/var/lib/mysql

  api:
    container_name: zoss_api
    image: renanmunizdev/teste-net-api:latest
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=zoss_test;User Id=root;Password=root;
    depends_on:
      - db

volumes:
  db_data:
